---
# handlers file for openldap

- name: start ldap
  service: name=slapd state=started enabled=yes

- name: restart ldap
  service: name=slapd state=restarted

- name: restart iptables
  service: name=iptables state=restarted enabled=yes

